# Generated by Django 3.1.2 on 2020-10-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Gender')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
            ],
        ),
    ]
